_target_: model.clamp.CLaMPLite
datamodule:
  _target_: data.datamodule.CLaCDataModule
  data_path: ${paths.data}
  batch_size: ${hyperparams.batch_size}
  num_workers: ${hyperparams.num_workers}
  tokenizer_model: ${llm}
  debug: ${debug}  
  datatype: papers # narratives, papers
  sentencewise: True

augmentation: True

emb_dim: ${hyperparams.emb_dim}
defaults:
  - graph_encoder: painn
  - optimizer: adamw
  - scheduler: cosine
  - graph_augmentation1: attr_masking
  - graph_augmentation2: perturb_structure # attr_masking # perturb_structure
  - text_augmentation: token_random_masking
