_target_: model.clamp.GNNSSL
datamodule:
  _target_: data.datamodule.CLaMPDataModule
  data_path: ${paths.data}
  batch_size: ${hyperparams.batch_size}
  num_workers: ${hyperparams.num_workers}
  tokenizer_model: ${llm}
  debug: ${debug}

augmentation: True

emb_dim: ${hyperparams.emb_dim}
defaults:
  - graph_encoder: painn
  - optimizer: adamw
  - scheduler: cosinewarm
  - graph_augmentation1: attr_masking # attr_masking # perturb_structure
  - graph_augmentation2: perturb_structure # attr_masking # perturb_structure
