optimizer:
  #  Adam-oriented deep learning
  _target_: torch.optim.AdamW
  #  These are all default parameters for the Adam optimizer
  lr: 0.00002 # supervised 0.001, clamp 0.00002  0.0001
  betas: [ 0.9, 0.999 ]
  eps: 1e-08
  weight_decay: 0

use_lr_scheduler: True